name: Update PR Title and Body to 'closed'

on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Title and Body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER \
            -d '{"title": "closed", "body": "closed"}'
